AllCops:
  Exclude:
    - 'lib/colour_patch.rb'
    - 'Gemfile'
    - 'spec/spec_helper.rb'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/*'
    - 'spec/*/*'

Layout/LineLength:
  Exclude:
    - 'spec/*'
    - 'spec/*/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
