AllCops:
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/*'

Layout/LineLength:
  Exclude:
    - 'spec/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
